# Site settings
title: "EFT-TBT Groups"
email: eft-tbt@gmail.com
description: > # Site internet d’Isabelle Levrat — EFT–TBT Groups
locale: fr_FR
# url: "http://zoom-sante.com"
# baseurl: "/efttbtgroups" # the subpath of your site, e.g. /blog/

# url: "http://nichub.github.io/"
# baseurl: "/eft-tbt-v1" # the subpath of your site, e.g. /blog/

url: "http://eft-tbt.com/"
baseurl: "eft-tbt-v1"


# Build settings
markdown: kramdown
