# Site settings
title: "EFT-TBT Groups"
email: eft-tbt@gmail.com
description: > # Site internet d’Isabelle Levrat — EFT–TBT Groups
baseurl: "/efttbtgroups" # the subpath of your site, e.g. /blog/
url: "http://zoom-sante.com"


# Build settings
markdown: kramdown
