# Site settings
title: "EFT-TBT Groups"
email: eft-tbt@gmail.com
description: > # Site internet d’Isabelle Levrat — EFT–TBT Groups
# baseurl: "/efttbtgroups" # the subpath of your site, e.g. /blog/
# url: "http://zoom-sante.com"
baseurl: "/"
url: "http://nichub.github.io/eft-tbt-v1/"


# Build settings
markdown: kramdown
